### PR TITLE
Quality of life

### PR DESCRIPTION
**Pull request by aryanpingle**
* Enables the `watch` flag when using `npm run start`, so that changes restart the server
* Enables CORS so that different domains can use the API

### CODE REVIEW

**Review by alfaArghya — CHANGES_REQUESTED** [review]
image

This feature is currently in an experimental stage and subject to change 😨. In light of this, I propose switching to `nodemon index.js` 🙂 as an alternative, as it accomplishes the same tasks.

**Comment by aryanpingle** [comment]
Nice catch, yeah I second that proposal

**Comment by alfaArghya** [comment]
yeah, I will check that by today ☺️

**Comment by alfaArghya** [comment]
Your code works fine 🎉
😶‍🌫️However I found an npm package for CORS, and I think it will make the codebase cleaner.

🔗https://www.npmjs.com/package/cors
💡Please read this documentation and tell me your thoughts about it. 🤔

**Pull request closed without merging**
