### PR TITLE
Update userData.ts

### PR DESCRIPTION
**Pull request by mahdiehmortazavi**
add discuss, views, and solution

### CODE REVIEW

**Review by alfaarghya — COMMENTED** [review]
TS types are not included & other than that you don't even write GraphQl queries.

**Comment by mahdiehmortazavi** [comment]
@alfaarghya so,its not possible to fetch all discussion for each user?

**Comment by alfaarghya** [comment]
@mahdiehmortazavi , I don't know if the queries are available or not, but if u want to get the data u need to add graphQl queries, because in my code I don't have those queries.

So first try to add those queries in `GQLQueries` folder, and check if it's possible or not And don't forget to add types

**Comment by mahdiehmortazavi** [comment]
@alfaarghya Thank you for your reply, but since I am not a professional in writing queries with graphql, could you please give me more guidance?

**Comment by alfaarghya** [comment]
Yeah Sure!! But I am not professional also 😅

Try to visit `src/GQLQueries`! Here are all of the queries that me and contributors found. Please try to understand them. 
You need to change `src/GQLQueries/userProfile.ts`.

**Comment by mahdiehmortazavi** [comment]
Tnx a lot

**Pull request closed without merging**
