### PR TITLE
Added filtering based on diffiuclty

### PR DESCRIPTION
**Pull request by P-M-Manmohan**
This is my first contribution to open source, so apologies if this is not the proper way to do it or if i did something incorrectly please correct me if i did.

I tried adding a filtering based on difficulty of the leetcode problems ( I didnt see this feature in the documentation ).

### CODE REVIEW

**Comment by alfaarghya** [comment]
That's great 💙!

let's make this contribution successful!

**Comment by alfaarghya** [comment]
> This is my first contribution to open source, so apologies if this is not the proper way to do it or if i did something incorrectly please correct me if i did.
> 
> I tried adding a filtering based on difficulty of the leetcode problems ( I didnt see this feature in the documentation ).

Yeah difficulty filter is not added cuz it's difficult to add 😅

**Comment by alfaarghya** [comment]
So did u check the code before committing? Is it working fine?

when I tried `/problems?difficulty=hard`, this is my result - 
image

**Comment by P-M-Manmohan** [comment]
It has to be in capital letters

**Comment by P-M-Manmohan** [comment]
EASY/MEDIUM/HARD

**Comment by alfaarghya** [comment]
> EASY/MEDIUM/HARD

Got it 👍

**Review by alfaarghya — APPROVED** [review]
Good to Go 🏃‍♂️‍➡️

**Comment by alfaarghya** [comment]
### 🎉 @P-M-Manmohan Thanks for your contribution! 😊
Your code looks great, and I appreciate the thoroughness of your work. The enhancements you added are well-implemented, and I've reviewed everything. I'm happy to approve it for merging. 🚀 Thanks again for your valuable contribution 😄

**Pull request merged**
