### PR TITLE
Add Descriptions and Methods to API route documentation.

### PR DESCRIPTION
**Pull request by 123xylem**
To enable this api domain to be whitelisted on sites like pythonanywhere.com the api documentation had to be improved. This PR adds some Descriptions and Method descriptions to the routes.

### CODE REVIEW

**Comment by 123xylem** [comment]
I have added a link to the official readme of this repo.
This links the api domain to the documentation.
This will allow it to be whitelisted on sites like pythonanywhere.com so that others can use it in their projects.

**Review by alfaarghya — APPROVED** [review]
Good to Go 🏃‍♂️

**Comment by alfaarghya** [comment]
### 🎉 @123xylem  Thanks for your contribution! 😊
Your code looks great, and I appreciate the thoroughness of your work. The enhancement you added are well-implemented, and I've reviewed everything. I'm happy to approve it for merging. 🚀 Thanks again for your valuable contribution 😄

**Comment by 123xylem** [comment]
Thankyou 😁👍

**Pull request merged**
