### PR TITLE
docs: update contributing wording

### PR DESCRIPTION
**Pull request by sazsu**
- use consistent capitalization
- improve clarity of instructions
- fix typos
- correct grammatical errors

### CODE REVIEW

**Comment by alfaarghya** [comment]
### hii @sazsu 👋

First, I appreciate your work. If you are interested in contributing, please contribute in code rather than documentation. Your changes do not affect any major documentation, **so I think it's fine, and I will merge it after your response in this thread🧵**. However, I cannot add your name to the documentation because it's not a code contribution.

💡A small piece of advice - If you want to change or update the documentation in any repo, first you need permission.

**Comment by sazsu** [comment]
Hi, yeah, first time contributing, and I appreciate your advice. As for the name, it’s not a big deal to me — I just wanted to contribute because this project looked interesting to me.

**Comment by alfaarghya** [comment]
> Hi, yeah, first time contributing, and I appreciate your advice. As for the name, it’s not a big deal to me — I just wanted to contribute because this project looked interesting to me.

Thank you for your understanding! 🙂‍↕️😊

**Comment by alfaarghya** [comment]
### 🎉 Thanks for your contribution! 😊

**Pull request merged**
